### ISSUE TITLE
When I was training data, I encountered an error

### ISSUE THREAD

**Issue by 386469007** [yrcong/RelTR#50]
Hello, I am very interested in your research. I have created my own dataset (with new categories and relationships added), and the format of the dataset is the same as in your code. But when I was training data, I encountered an error, but I couldn't find the problem with my dataset format. Is there any aspect of the code that needs to be adjusted? Can you help me?

The error is as follows：

C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [61,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: block: [0,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "main.py", line 240, in <module>
    main(args)
  File "main.py", line 192, in main
    train_stats = train_one_epoch(model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm)
  File "E:\LXD\RelTR-main\engine.py", line 40, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "E:\Anaconda3\envs\reltr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\LXD\RelTR-main\models\reltr.py", line 299, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "E:\Anaconda3\envs\reltr\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\envs\reltr\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "E:\LXD\RelTR-main\models\matcher.py", line 112, in forward
    cost_sub_giou = -generalized_box_iou(box_cxcywh_to_xyxy(sub_bbox), box_cxcywh_to_xyxy(sub_tgt_bbox))
  File "E:\LXD\RelTR-main\util\box_ops.py", line 50, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all(), boxes1
RuntimeError: CUDA error: device-side assert triggered

**Comment by ikram-md** [comment]
Hi, could you please share how were you able to solve this problem because i am facing it as well with my custom dataset ! 
![image](https://github.com/yrcong/RelTR/assets/56800980/2001ef19-8429-418c-a61b-2cc96903cc9c)

**Comment by IceIce1ce** [comment]
+1
